"""
core/orchestrator.py

Builds and returns the compiled LangGraph application for the
Compliance Monitoring System.

Graph Topology:
  regulatory_tracker
        │
        ▼
  transaction_monitor
        │
        ▼
  communication_scanner
        │
        ▼
  conflict_resolution
        │
   ┌────┴────────────┐
   ▼                 ▼
hitl_placeholder   report_generator ──► END
        │
        ▼
  report_generator ──► END
"""

import os
import uuid
from typing import Dict, Any, List, Set
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables and Docker secret early
load_dotenv()
secret_path = os.getenv("GOOGLE_API_KEY_FILE")
if secret_path and os.path.exists(secret_path):
    try:
        with open(secret_path, "r") as fh:
            key = fh.read().strip()
        if key:
            os.environ["GOOGLE_API_KEY"] = key
    except Exception:
        pass

from langgraph.graph import StateGraph, END
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from langgraph.checkpoint.memory import MemorySaver

from core.state import ComplianceState
from core.models import AlertList
from agent.regulatory_tracker import get_regulatory_tracker_node
from agent.transaction_monitor import get_transaction_monitor_node
from agent.communication_scanner import get_communication_scanner_node

_GOOGLE_KEY_PRESENT = (
    bool(os.getenv("GOOGLE_API_KEY"))
    and os.getenv("GOOGLE_API_KEY") != "your_google_api_key_here"
)


# ── Stub nodes (to be replaced in Days 7/10/11) ──────────────────────────────

# ── Correlation Engine (Day 9) ───────────────────────────────────────────────

_TX_AGENT_KEYWORDS   = {"Transaction", "transaction", "TRANSACTION"}
_COMM_AGENT_KEYWORDS = {"Communication", "communication", "COMMUNICATION", "Compliance AI"}


def _agent_type(source_agent: str) -> str:
    """Classify an alert by its source agent type for cross-reference matching."""
    if any(kw in source_agent for kw in _TX_AGENT_KEYWORDS):
        return "TRANSACTION"
    if any(kw in source_agent for kw in _COMM_AGENT_KEYWORDS):
        return "COMMUNICATION"
    return "OTHER"


def conflict_resolution_node(state: ComplianceState) -> Dict[str, Any]:
    """
    Day 9 Correlation Engine (Semantic Upgraded).
    """
    print("--- AGENT: CORRELATION ENGINE (Semantic Resolution) ---")
    alerts = state.get("alerts", [])
    
    if not alerts:
        return {"alerts": []}

    # Format alerts for the LLM prompt
    formatted_alerts = [
        {
            "alert_id": a.get("alert_id"),
            "source_agent": a.get("source_agent"),
            "entity_id": a.get("entity_id"),
            "risk_level": a.get("risk_level"),
            "reason": a.get("reason"),
            "entities_involved": a.get("entities_involved", []),
            "timestamp": a.get("timestamp")
        } for a in alerts
    ]
    
    new_meta_alerts = []

    if _GOOGLE_KEY_PRESENT:
        llm = ChatGoogleGenerativeAI(
            model="gemini-3.1-flash-lite",
            api_key=os.getenv("GOOGLE_API_KEY"),
            temperature=0,
        )
        analyzer_llm = llm.with_structured_output(AlertList)

        prompt = ChatPromptTemplate.from_messages([
            ("system", """You are the Lead Correlation Engine for a Tier-2 Bank.
Your job is to read all the compliance alerts generated by the Transaction Monitor and Communication Scanner.

Look for SEMANTIC LINKS across different alerts. A coordinated breach might involve different entities.
Example: 
- Alert A (Communication): SPOUSE_001 mentions "Buy TSLA now, John gave me the signal."
- Alert B (Transaction): TRADER_007 executes a massive TSLA buy 2 minutes later.

If you find semantic links (matching tickers, closely aligned timestamps, explicit mentions), 
generate a CRITICAL META-ALERT that fuses them together. 
- The 'alert_id' MUST start with 'META_'
- The 'entities_involved' should list ALL linked entities (e.g. SPOUSE_001, TRADER_007).
- The 'reason' must explicitly explain the semantic link you found.
- The 'linked_alert_ids' must contain the original alert IDs.

Do NOT generate new alerts for isolated events. ONLY generate META-ALERTs for correlated events.
"""),
            ("user", "Generated Alerts:\n{alerts}")
        ])

        chain = prompt | analyzer_llm

        try:
            print("INFO [CorrelationEngine]: Running semantic reasoning over alerts...")
            llm_output = chain.invoke({
                "alerts": formatted_alerts
            })
            
            if llm_output and hasattr(llm_output, 'alerts'):
                for meta_alert in llm_output.alerts:
                    meta_alert.alert_id = f"META_{uuid.uuid4().hex[:8].upper()}"
                    meta_alert.source_agent = "Correlation Engine (Semantic)"
                    meta_alert.risk_level = "CRITICAL"
                    meta_alert.entity_type = "CORRELATED_ENTITY"
                    new_meta_alerts.append(meta_alert.to_state_dict())
                    print(f"  [META-ALERT] {meta_alert.alert_id}: {meta_alert.reason[:80]}...")
                    
        except Exception as e:
            print(f"Error in Semantic Correlation: {e}")
    else:
        print("INFO [CorrelationEngine]: No API key present. Skipping semantic matching.")

    # Calculate overall escalation status based on ALL alerts
    all_alerts_combined = alerts + new_meta_alerts
    severity_rank = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1}
    max_rank = max(
        (severity_rank.get(a.get("risk_level", "LOW").upper(), 0)
         for a in all_alerts_combined),
        default=0,
    )
    max_severity = {v: k for k, v in severity_rank.items()}.get(max_rank, "NONE")

    if max_rank >= 4:
        escalation = "ESCALATED"
    elif max_rank >= 3:
        escalation = "PENDING_REVIEW"
    else:
        escalation = "NONE"

    # Gather all flagged entities
    all_entity_ids = list({
        eid
        for a in all_alerts_combined
        for eid in ([a.get("entity_id", "")] + a.get("entities_involved", []) + a.get("linked_alert_ids", []))
        if eid and not eid.startswith("ALERT") and not eid.startswith("META")
    })

    print(
        f"INFO [CorrelationEngine]: {len(new_meta_alerts)} META-ALERT(s) generated. "
        f"Max severity: {max_severity}. Escalation: {escalation}."
    )

    return {
        "escalation_status": escalation,
        "flagged_entities":  all_entity_ids,
        "alerts":            new_meta_alerts,
    }


def hitl_placeholder_node(state: ComplianceState) -> Dict[str, Any]:
    """
    Placeholder for Human-in-the-Loop (Day 11).
    In the full build this will use LangGraph's interrupt() to pause execution
    and surface the case to the Streamlit Compliance Officer Dashboard.
    """
    print("--- HITL PLACEHOLDER (Day 11 implementation pending) ---")
    print(f"  Escalation status: {state.get('escalation_status')}")
    print(f"  Flagged entities:  {state.get('flagged_entities')}")
    # For now, auto-approve to let execution continue
    return {"human_feedback": "AUTO_APPROVED_FOR_TESTING"}


def report_generator_node(state: ComplianceState) -> Dict[str, Any]:
    """
    Full report generator — uses Gemini 2.5 Flash to synthesise a professional
    Markdown compliance audit report from all accumulated alerts.
    Falls back to a clean template if no API key is available.
    """
    print("--- AGENT 4: REPORT GENERATOR ---")
    alerts = state.get("alerts", [])
    rules  = state.get("active_rules", [])
    escalation = state.get("escalation_status", "NONE")
    flagged    = state.get("flagged_entities", [])
    run_ts     = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    human_feedback = state.get("human_feedback", "")

    if human_feedback and human_feedback.startswith("REJECTED"):
        reject_reason = human_feedback.replace("REJECTED:", "").strip()
        report = (
            "# 🛑 Investigation Rejected by Compliance Officer\n\n"
            f"**Generated**: {run_ts}\n\n"
            "This investigation was manually reviewed and dismissed.\n\n"
            f"**Rejection Reason**: {reject_reason}\n\n"
            "All underlying alerts have been archived and this entity pattern has been added to the ChromaDB False Positives feedback loop. No further action is required."
        )
        print("INFO [ReportGenerator]: Alerts were rejected by human. Bypassing LLM synthesis.")
        return {"report_content": report}

    # ── Fallback template (no LLM) ───────────────────────────────────────────
    def _build_fallback_report() -> str:
        lines = [
            "# Compliance Monitoring Audit Report",
            f"**Generated**: {run_ts}",
            f"**Escalation Status**: {escalation}",
            f"**Total Alerts**: {len(alerts)}",
            f"**Flagged Entities**: {', '.join(flagged) if flagged else 'None'}",
            "",
            "---",
            "",
            "## Active Regulatory Rules Retrieved",
        ]
        if rules:
            for r in rules:
                lines.append(f"- **{r.get('jurisdiction','?')}**: {r.get('description','')[:120]}...")
        else:
            lines.append("_No rules retrieved from ChromaDB (vector store not yet ingested)._")
        lines += ["", "---", "", "## Compliance Alerts"]
        if alerts:
            for i, a in enumerate(alerts, 1):
                lines.append(
                    f"### Alert {i}: [{a.get('risk_level','N/A')}] {a.get('source_agent','?')}\n"
                    f"- **Entity**: `{a.get('entity_id','?')}` ({a.get('entity_type','?')})\n"
                    f"- **Reason**: {a.get('reason','?')}\n"
                    f"- **Timestamp**: {a.get('timestamp','?')}"
                )
        else:
            lines.append("_No compliance violations detected._")
        lines += ["", "---", "", "## Verdict",
                  f"Overall escalation status: **{escalation}**. "
                  "Review flagged entities and escalate to Compliance Officer if required."]
        return "\n".join(lines)

    # ── LLM synthesis ────────────────────────────────────────────────────────
    report: str
    if not _GOOGLE_KEY_PRESENT or not alerts:
        report = _build_fallback_report()
        if not alerts:
            print("INFO [ReportGenerator]: No alerts — using clean-bill template.")
    else:
        try:
            llm = ChatGoogleGenerativeAI(
                model="gemini-3.1-flash-lite",
                api_key=os.getenv("GOOGLE_API_KEY"),
                temperature=0.2,
                max_output_tokens=2048,
            )
            prompt = ChatPromptTemplate.from_messages([
                ("system",
                 "You are a Senior Compliance Officer writing a formal audit report for a Tier-2 Bank. "
                 "You will be given: (1) regulatory rules from a vector store, "
                 "(2) compliance alerts from automated agents, which may include special META-ALERTs "
                 "from the Correlation Engine (source_agent = 'Correlation Engine (META)').\\n\\n"
                 "META-ALERTs indicate that the SAME entity was flagged by BOTH the Transaction Monitor "
                 "AND the Communication Scanner — this is a multi-channel coordinated breach pattern "
                 "and must be treated with the HIGHEST urgency.\\n\\n"
                 "Write a professional Markdown audit report with these sections:\\n"
                 "1. Executive Summary (lead with any coordinated breach findings)\\n"
                 "2. Regulatory Framework (cite each rule by its jurisdiction/rule ID)\\n"
                 "3. Coordinated Breach Analysis — ONLY if META-ALERTs exist: one sub-section per "
                 "   META-ALERT, showing the linked_alert_ids evidence chain and why the co-occurrence "
                 "   elevates the risk beyond the individual alerts\\n"
                 "4. Individual Findings (one sub-section per unique entity_id for non-META alerts)\\n"
                 "5. Risk Matrix (table: Entity | Violation Type | Source | Risk Level | Recommended Action)\\n"
                 "6. Recommended Actions (prioritise CRITICAL and CORRELATED_ENTITY entities first)\\n"
                 "7. Conclusion\\n"
                 "Be precise — cite alert IDs, rule IDs, and the full entity ID trail for each finding."),
                ("user",
                 "Run timestamp: {run_ts}\\n"
                 "Escalation status: {escalation}\\n"
                 "Flagged entities: {flagged}\\n\\n"
                 "=== REGULATORY RULES RETRIEVED FROM CHROMADB ===\\n{rules}\\n\\n"
                 "=== ALL COMPLIANCE ALERTS (including META-ALERTs from Correlation Engine) ===\\n{alerts}"),
            ])
            chain = prompt | llm
            response = chain.invoke({
                "run_ts":     run_ts,
                "escalation": escalation,
                "flagged":    ", ".join(flagged) if flagged else "None",
                "rules":      rules,
                "alerts":     alerts,
            })
            if isinstance(response.content, list):
                report = "".join(
                    chunk["text"] if isinstance(chunk, dict) and "text" in chunk
                    else str(chunk)
                    for chunk in response.content
                )
            else:
                report = response.content
            print("INFO [ReportGenerator]: LLM synthesis complete.")
        except Exception as e:
            print(f"ERROR [ReportGenerator]: LLM synthesis failed ({e}). Using fallback.")
            report = _build_fallback_report()

    print(report[:500] + "...\n[truncated]" if len(report) > 500 else report)
    return {"report_content": report}


# ── Router ───────────────────────────────────────────────────────────────────

def _route_after_conflict_resolution(state: ComplianceState) -> str:
    """
    Routes to HITL for CRITICAL/HIGH alerts; direct to report for everything else.
    """
    status = state.get("escalation_status", "NONE")
    if status in ("ESCALATED", "PENDING_REVIEW"):
        return "hitl_placeholder"
    return "report_generator"


# ── Graph Builder ─────────────────────────────────────────────────────────────

def build_orchestrator(enable_hitl=True):
    """
    Compiles and returns the LangGraph application.
    Call once at startup and reuse the compiled app.
    """
    workflow = StateGraph(ComplianceState)

    # Register nodes
    workflow.add_node("regulatory_tracker",    get_regulatory_tracker_node())
    workflow.add_node("transaction_monitor",   get_transaction_monitor_node())
    workflow.add_node("communication_scanner", get_communication_scanner_node())
    workflow.add_node("conflict_resolution",   conflict_resolution_node)
    workflow.add_node("hitl_placeholder",      hitl_placeholder_node)
    workflow.add_node("report_generator",      report_generator_node)

    # Sequential edges
    workflow.set_entry_point("regulatory_tracker")
    workflow.add_edge("regulatory_tracker",    "transaction_monitor")
    workflow.add_edge("transaction_monitor",   "communication_scanner")
    workflow.add_edge("communication_scanner", "conflict_resolution")

    # Conditional edge: escalate or report directly
    workflow.add_conditional_edges(
        "conflict_resolution",
        _route_after_conflict_resolution,
        {
            "hitl_placeholder": "hitl_placeholder",
            "report_generator": "report_generator",
        },
    )

    # HITL always leads to report after human review
    workflow.add_edge("hitl_placeholder", "report_generator")
    workflow.add_edge("report_generator", END)

    if enable_hitl:
        # langgraph 0.2.x + langgraph-checkpoint-sqlite 1.0.x
        try:
            from langgraph.checkpoint.sqlite import SqliteSaver
        except ImportError:
            print("WARNING [Orchestrator]: SqliteSaver unavailable — falling back to MemorySaver.")
            return workflow.compile(
                checkpointer=MemorySaver(),
                interrupt_before=["report_generator"]
            )

        db_path = "checkpoints.sqlite"
        import sqlite3
        # Connect explicitly so the connection stays open for the lifetime of the app
        conn = sqlite3.connect(db_path, check_same_thread=False)
        memory = SqliteSaver(conn)
        if hasattr(memory, "setup"):
            memory.setup()

        return workflow.compile(
            checkpointer=memory,
            interrupt_before=["report_generator"]
        )
    else:
        return workflow.compile()

# Expose a globally compiled app instance for the Streamlit dashboard
app = build_orchestrator(enable_hitl=True)


# ── Quick smoke-test ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = build_orchestrator()
    print("[OK] Orchestrator compiled successfully. Running smoke test...\n")

    initial_state: ComplianceState = {
        "current_transaction": {
            "transaction_id": "TEST_TX_123",
            "trader_id": "TRADER_007",
            "symbol": "TSLA",
            "quantity": 500,
            "price": 200.0,
            "timestamp": "2026-05-22T10:00:00",
            "order_type": "MARKET",
            "asset_class": "EQUITY",
        },
        "current_loan": None,
        "current_communication": {
            "comm_id": "TEST_MSG_456",
            "sender_id": "EMP_001",
            "receiver_ids": ["CLIENT_007"],
            "channel": "WHATSAPP",
            "timestamp": "2026-05-22T11:00:00",
            "content": "I can guarantee a 15% return. Don't use email, text me instead.",
        },
        "active_rules": [],
        "flagged_entities": [],
        "alerts": [],
        "regulatory_updates": [],
        "escalation_status": "NONE",
        "human_feedback": None,
        "report_content": None,
    }

    for step_output in app.stream(initial_state):
        node_name = list(step_output.keys())[0]
        print(f"\n[STEP: {node_name}]")
        print("----")
